# Site settings
title: Stefan Schulz
description: 'Computer scientist and educator'
url: 'https://rubyfi.de'
baseurl: ''
font_awesome: '57918ba98d.js'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Stefan Schulz'
  email: hallo@rubyfi.de
  twitter_username: 0xRubyfi
  github_username:  rubyfi
  google_scholar_username: VPbzSVMAAAAJ
  orcid_username: 0000-0002-8310-7676
  linkedin_username: stefan-schulz-017012114
  #youtube_channelid:
  #youtube_username:

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
        layout: 'default'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'docker-compose.yml', 'node_modules', 'vendor/bundle/', 'vendor/cache/', 'vendor/gems/', 'vendor/ruby/']