# Site settings
title: Stefan Schulz
description: 'IT Consultant & Computer Scientist'
url: 'https://rubyfi.de'
baseurl: ''
font_awesome: '57918ba98d.js'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Stefan Schulz'

# The order of the social links is defined by their order in this list
socials:
  github:
    user_id: rubyfi
  hackerrank:
    user_id: rubyfi
  scholar: 
    user_id: VPbzSVMAAAAJ
  orcid: 
    user_id: 0000-0002-8310-7676
  linkedin: 
    user_id: stefan-schulz-017012114
  twitter: 
    user_id: 0xRubyfi
  email: 
    address: hallo@rubyfi.de
  #reddit:
  #  user_id: rubyfi
  #youtube:
  #  channel_id:  
  #  display_name: (optional)
  #instagram:
  #  user_id: 
  #tiktok:
  #  user_id:
  #twitch:
  #  user_id:
  

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
        layout: 'default'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'docker-compose.yml', 'socials/', 'node_modules', 'vendor/bundle/', 'vendor/cache/', 'vendor/gems/', 'vendor/ruby/']
